### ISSUE TITLE
Ошибка при запуске проекта

### ISSUE THREAD

**Issue by nikitabobers** [razrabs-media/journal#291]
Получаю ошибку при попытке запуска проекта используя `npm run dev` :
```
TypeError [ERR_INVALID_URL]: Invalid URL
	at new NodeError (node:internal/errors:372:5)
	at URL.onParseError (node:internal/url:553:9)
	at parse (<anonymous>)
	at new URL (node:internal/url:629:5)
	at createApolloClient (webpack-internal:///./src/shared/api/apollo-client.ts:27:12)
	at initializeApollo (webpack-internal:///./src/shared/api/apollo-client.ts:37:114)
	at Function.App.getInitialProps (webpack-internal:///./src/pages/_app.tsx:150:85)
	at async Object.loadGetInitialProps (/Users/user/journal/node_modules/next/dist/shared/lib/utils.js:65:19)
	at async Object.renderToHTML (/Users/user/journal/node_modules/next/dist/server/render.js:473:14)
	at async doRender (/Users/user/journal/node_modules/next/dist/server/base-server.js:870:38) {
input: 'api',
code: 'ERR_INVALID_URL'
}
```
**Environment:**
node: 16.16.0
chrome: 103.0.5060.134
macOS: 12.3.1

<img width="567" alt="Screenshot 2022-08-01 at 22 01 52" src="https://user-images.githubusercontent.com/58427328/182224767-ced4bb25-76e7-49c7-b637-233e8c9820bc.png">

**Comment by ninedev-i** [comment]
Раскомментируй все в `.env.development`
